import type { Metadata } from "next";
import { AppEntry } from "@/components/AppEntry";
import { PageShell } from "@/components/PageShell";
import { Reveal } from "@/components/Reveal";

export const metadata: Metadata = { title: "Funciones", description: "Conoce VITACOACH, entrenamiento adaptativo, nutrición y seguimiento semanal de VITAMATE." };

const functions = [
  { id: "vitacoach", label: "01 · COMPAÑÍA", title: "VITACOACH", lead: "Conversación que se convierte en progreso.", text: "Habla por chat o voz sobre lo que comiste, tu entrenamiento, cansancio, motivación o dudas. Con tu autorización, conserva recuerdos útiles para responder con continuidad.", items: ["Registra comidas y actividad desde una conversación", "Analiza fotografías de alimentos antes de confirmar", "Recuerda preferencias, objetivos y contexto relevante", "Resume las llamadas dentro del historial del chat"], visual: "chat" },
  { id: "entrenamiento", label: "02 · MOVIMIENTO", title: "Entrenamiento adaptativo", lead: "Una rutina estable que evoluciona contigo.", text: "Elige casa o gym. Registra cada set, repetición y peso. VITAMATE usa el historial para sugerir cuándo sumar una repetición o aumentar la carga dentro de un rango seguro.", items: ["Progresión semana a semana", "Registro set por set, sin castigar repeticiones incompletas", "Metas de actividad semanales en calorías", "Historial y retroalimentación al terminar"], visual: "workout" },
  { id: "nutricion", label: "03 · ALIMENTACIÓN", title: "Nutrición que sí cabe", lead: "Comidas, macros y súper en un solo plan.", text: "Recibe dos alternativas por comida, adaptadas a gustos, restricciones, habilidades, presupuesto y forma de cocinar. Elige una y el plan actualiza la semana.", items: ["Registro por búsqueda, código, fotografía o texto", "Porciones convertidas a gramos y macros calculados", "Meal prep o variedad diaria", "Lista semanal consolidada y estimación de costo"], visual: "nutrition" },
  { id: "progreso", label: "04 · CONTINUIDAD", title: "Progreso con perspectiva", lead: "Datos para decidir, no para juzgar.", text: "Consulta días o periodos, entiende excesos y déficits, actualiza tus metas y vuelve a responder el quiz cuando tu vida cambie.", items: ["Balance semanal flexible", "Metas editables", "Historial de peso, comida y actividad", "Respaldo de cuenta en la nube"], visual: "progress" },
] as const;

function FunctionVisual({ kind }: { kind: string }) {
  if (kind === "chat") return <div className="function-mock chat-mini"><div className="mini-head"><span className="coach-orb small">VC</span><b>VITACOACH</b><i /></div><p className="mine">Registra mi desayuno: huevos, tortillas y salsa.</p><p className="theirs">Listo. Preparé una estimación para que confirmes cantidades.</p><span className="mini-confirm">Revisar y registrar →</span></div>;
  if (kind === "workout") return <div className="function-mock workout-mini"><div className="mini-label">PRESS INCLINADO · SET 2/3</div><strong>5 <small>/ 6 reps</small></strong><div className="rep-dots">{[1,2,3,4,5,6].map(i => <i key={i} className={i < 6 ? "active" : ""} />)}</div><div className="weight-row"><span>Carga actual</span><b>100 kg</b></div><button>+ 1 repetición</button></div>;
  if (kind === "nutrition") return <div className="function-mock nutrition-mini"><span className="mini-label">COMIDA · OPCIÓN A</span><div className="meal-shape"><i /><div><b>Pollo al limón</b><small>Arroz integral · vegetales</small></div></div><div className="nutrition-values"><span><b>540</b> kcal</span><span><b>46 g</b> proteína</span></div><button>Elegir y registrar</button></div>;
  return <div className="function-mock progress-mini"><span className="mini-label">BALANCE SEMANAL</span><div className="big-progress"><strong>82%</strong><i><b /></i></div><div className="balance-row"><span>Proteína</span><b>− 24 g</b></div><div className="balance-row"><span>Actividad</span><b>− 380 kcal</b></div></div>;
}

export default function FunctionsPage() {
  return <PageShell><section className="subhero section-shell"><Reveal><span className="eyebrow">Una experiencia conectada</span><h1>Todo lo que necesitas.<br /><em>Sin vivir para medirlo.</em></h1><p>Cuatro sistemas que comparten contexto para darte una orientación coherente, práctica y personal.</p></Reveal></section><section className="function-sections section-shell">{functions.map((item, index) => <article id={item.id} key={item.id} className={index % 2 ? "reverse" : ""}><Reveal className="function-copy"><span className="eyebrow">{item.label}</span><h2>{item.title}</h2><h3>{item.lead}</h3><p>{item.text}</p><ul>{item.items.map(value => <li key={value}><span>✓</span>{value}</li>)}</ul></Reveal><Reveal className="function-visual-wrap" delay={100}><FunctionVisual kind={item.visual} /></Reveal></article>)}</section><section className="simple-cta section-shell"><Reveal><h2>Tu información cobra sentido cuando trabaja junta.</h2><p>Configura tus objetivos y recibe tu primera semana personalizada.</p><AppEntry>Comenzar con VITAMATE <span>→</span></AppEntry></Reveal></section></PageShell>;
}
