import { fal } from '@fal-ai/client';
import { config } from '../config.js';

export class FalExerciseMediaProvider {
  constructor() {
    if (config.FAL_KEY) fal.config({ credentials: config.FAL_KEY });
  }

  async generate(input: { slug: string; name: string; instructions: string[]; safetyNotes: string[] }) {
    if (!config.FAL_KEY) throw new Error('FAL_KEY no está configurada.');
    const exactMovement: Record<string, string> = {
      squat: 'ONE SINGLE three-quarter-view athlete at the bottom of a BARBELL BACK SQUAT: straight bar secured across upper back, feet shoulder-width, hips back and down, thighs approximately parallel, heels flat, knees tracking over toes, chest controlled. This is not a lunge.',
      'romanian-deadlift': 'ONE SINGLE true side-view athlete at the lowest controlled point of a BARBELL ROMANIAN DEADLIFT. ONE straight bar is held with both arms vertical and touches the front of the legs just below the knees. Hips are pushed dramatically backward, torso long and almost parallel to floor, spine neutral, shins vertical, knees only 15–20 degrees bent, heels flat. The bar never touches the floor. Not a squat, conventional deadlift, sumo deadlift, row or good morning; no deep knee bend and no rounded back.',
      'chest-press': 'ONE SINGLE side-view athlete lying supine on a flat weight bench in the bottom position of a BARBELL BENCH PRESS: both hands on one straight bar above mid-chest, elbows bent about 75 degrees, forearms vertical, shoulder blades on bench, feet flat. Never standing.',
      row: 'ONE SINGLE unobstructed left-side three-quarter-view athlete performing the TOP CONTRACTED position of a free-standing BARBELL BENT-OVER ROW. Both hands use a pronated shoulder-width grip on ONE horizontal straight bar located directly against the lower ribs and upper abdomen. Both elbows point backward and finish behind the torso. Torso remains rigid and hinged approximately 45 degrees, hips back, knees only softly bent, shins vertical. Bar stays in FRONT of the thighs and below the chest. Empty studio floor: absolutely NO rack, NO support, NO bench, NO cable and NO second bar. Not a curl, upright row, deadlift, clean, shrug or behind-neck movement.',
      'reverse-lunge': 'ONE SINGLE side-view athlete at the bottom of a REVERSE LUNGE: right foot is clearly stepped behind the body, left front foot completely flat, both knees near 90 degrees, right rear knee close to floor, torso vertical. This is not a forward lunge or running.',
      'shoulder-press': 'ONE SINGLE front three-quarter-view athlete standing in the top position of a BARBELL OVERHEAD PRESS: both hands on one straight bar directly above shoulders and mid-foot, elbows nearly straight, ribs down, glutes engaged, spine neutral.',
      plank: 'ONE SINGLE true side-view static LOW FOREARM PLANK. BOTH forearms lie flat on the floor from elbow to closed fist; elbows are directly below shoulders. Neither palm supports body weight. Both toes contact floor. Ears, shoulders, hips, knees and ankles form one straight horizontal line; hips neither sag nor pike. No high plank, push-up, lunge, crawling, raised limb or hands-and-knees pose.',
      'moderate-cardio': 'ONE single side-view adult walking briskly on a treadmill at moderate conversational effort, upright relaxed posture, natural opposite arm swing, both feet anatomically correct. This is steady cardio, not strength training.',
      'incline-barbell-press': 'ONE SINGLE side-view adult lying on a weight bench whose backrest is CLEARLY AND VISIBLY raised to a 30-degree incline, in the bottom position of an INCLINE BARBELL PRESS: head and torso visibly slope upward, hips remain on seat, shoulder blades set, feet flat, one straight bar just above the upper chest, forearms vertical, both hands gripping that same bar. This must not look like a flat bench press.',
      'lat-pulldown': 'ONE adult seated at a lat-pulldown machine in the contracted position: thighs secured under pads, torso nearly upright, wide bar pulled to upper chest, elbows down and slightly behind the ribs.',
      'leg-press': 'ONE SINGLE adult inside a clearly recognizable 45-DEGREE SLED LEG PRESS MACHINE, photographed from the open side at the controlled bottom position. Back, head and pelvis are fully supported by the inclined seat pad; both feet are flat and shoulder-width on ONE large rectangular footplate above the torso; knees are bent near 90 degrees and track over toes; hands hold the seat handles. The loaded sled rails and footplate are fully visible. No barbell, no shoulder press, no seated chest press and no squat.',
      'lateral-raise': 'ONE SINGLE front-view standing adult frozen at the TOP of a strict DUMBBELL LATERAL RAISE. Exactly ONE small dumbbell in EACH hand, two total. Both arms extend out to the LEFT and RIGHT sides in a wide T shape at shoulder height, elbows softly bent, palms angled toward floor, hands far from head, torso vertical. Dumbbells are NOT overhead and NOT being pressed; elbows are not flexed like a curl. No shoulder press, front raise, upright row or bent-over raise.',
      'barbell-curl': 'ONE standing adult at the contracted position of a straight-bar biceps curl: elbows fixed beside torso, forearms flexed, bar near lower chest, wrists neutral, no body swing.',
      'triceps-pressdown': 'ONE SINGLE side three-quarter-view standing adult at a HIGH CABLE station frozen at the BOTTOM of a ROPE TRICEPS PRESSDOWN. Cable descends vertically from a pulley above the head to one rope attachment. Upper arms are vertical and glued to the ribs, elbows fully extended, both hands beside the outer thighs, rope ends separated outward. Torso upright with a slight athletic lean. No lat pulldown, row, overhead extension, curl or shoulder movement.',
      'standing-calf-raise': 'ONE SINGLE true side-view adult frozen at the TOP of a TWO-LEG STANDING CALF RAISE on a low stable step. Both forefeet are on the step edge and BOTH heels are visibly lifted several centimeters above the step, ankles fully plantar-flexed, legs vertical, knees straight but unlocked. Fingertips lightly touch a wall only for balance. No raised knee, kick, jump, handstand or leg swing.',
      'kneeling-cable-crunch': 'ONE SINGLE strict side-view adult KNEELING directly below a HIGH CABLE pulley in the fully CONTRACTED KNEELING CABLE CRUNCH. Both knees and shins remain on a mat, hips stay vertically above knees and do NOT sit on heels. Rope ends are held motionless beside the temples; elbows point down. The thoracic spine is visibly flexed so the rib cage curls toward the pelvis and forehead approaches the floor. The cable remains taut from above. Arms do not pull down. No lat pulldown, triceps pressdown, prayer pose or hip hinge.',
      'goblet-squat': 'ONE adult at the bottom of a goblet squat: single dumbbell held vertically against chest, heels flat, knees aligned with toes, hips between thighs, spine neutral.',
      'push-up': 'ONE adult in the bottom position of a strict push-up: hands slightly wider than shoulders, elbows around 45 degrees, chest close to floor, body in one straight line from head to heels.',
      'one-arm-row': 'ONE SINGLE side three-quarter-view adult at the TOP of a BENCH-SUPPORTED ONE-ARM DUMBBELL ROW. LEFT hand and LEFT knee are planted on one flat bench; RIGHT foot is on floor; torso is horizontal and neutral. Exactly ONE dumbbell exists, held in the RIGHT hand against the right lower ribs, right elbow pulled high and backward close to the body. The working forearm remains vertical beneath the elbow. No second dumbbell, no curl, no seated pose, no barbell and no cable.',
      'backpack-romanian-deadlift': 'ONE SINGLE true side-view adult at the lowest controlled point of a ROMANIAN DEADLIFT using ONE CLOSED BACKPACK AS A HAND-HELD WEIGHT. The backpack is IN FRONT of the shins and held by BOTH hands gripping its top handle; both shoulder straps hang empty and the backpack is absolutely NOT worn on the back or shoulders. Hips pushed far backward, shins vertical, knees slightly bent, spine neutral, heels flat. Not a squat, row or conventional deadlift.',
      'home-reverse-lunge': 'ONE adult at the bottom of a reverse lunge at home: rear foot clearly stepped backward, front foot flat, both knees near 90 degrees, torso vertical, no running pose.',
      'pike-push-up': 'ONE adult in the bottom position of a pike push-up: hips high in an inverted V, hands flat, elbows bent back, crown of head approaching the floor between hands, heels raised naturally.',
      'split-squat': 'ONE SINGLE side-view adult frozen at the BOTTOM of a STATIONARY SPLIT SQUAT. LEFT foot stays forward completely flat; RIGHT foot stays behind on the ball of the foot; stance is long and fixed. Both knees are bent near 90 degrees, rear knee two centimeters above floor, torso upright and centered between the feet. No bench, no elevated rear foot, no dumbbells, no bilateral squat, no walking, running or stepping motion.',
      'glute-bridge': 'ONE adult supine at the top of a glute bridge: shoulders and feet on floor, knees bent, pelvis raised until shoulders-hips-knees form one line, ribs down, no excessive back arch.',
      'dead-bug': 'ONE SINGLE adult lying SUPINE on a mat, photographed from a high side three-quarter angle, frozen in the CONTRALATERAL DEAD BUG position. LEFT arm is extended straight overhead near the floor while RIGHT leg is extended straight forward with heel hovering above floor. At the same time RIGHT arm points vertically to ceiling and LEFT hip and knee remain stacked at exactly 90 degrees. Low back stays pressed to mat. Exactly two arms and two legs; no bicycle crunch, no both limbs extended on same side, no sitting.',
      'backpack-curl': 'ONE SINGLE front three-quarter-view standing adult at the TOP of a TWO-HANDED BACKPACK BICEPS CURL. ONE closed weighted backpack hangs IN FRONT of the torso, not worn. Each hand grips one short top or shoulder strap near the bag; both elbows are fixed beside the waist and bent, raising the backpack toward the lower chest. Both backpack shoulder straps are visibly OFF the shoulders. No backpack on back, no front carry harness, no squat, no upright row and no overhead lift.',
      'chair-triceps-dip': 'ONE SINGLE side-view adult at the controlled BOTTOM of a CHAIR TRICEPS DIP. One sturdy chair is visibly braced against a wall. The athlete is IN FRONT of the seat, hips completely OFF the front edge and suspended in air; both palms press on the seat beside the hips; elbows bend straight backward near 90 degrees; legs extend forward with heels on floor. The athlete is not sitting. No bench press, push-up, squat or hands behind the back.',
      'single-leg-calf-raise': 'ONE SINGLE true side-view adult frozen at the TOP of a SINGLE-LEG CALF RAISE beside a wall. The LEFT forefoot is planted on a low step and the LEFT heel is visibly lifted high by ankle plantar-flexion; left knee stays straight. The RIGHT knee is only slightly bent and right foot floats quietly behind without kicking. Fingertips lightly touch the wall. No handstand, leg raise, high kick, jump or lunge.',
    };
    const exactPrompt = exactMovement[input.slug];
    const prompt = [
      exactPrompt
        ? `REALISTIC EXERCISE REFERENCE PHOTO. ${exactPrompt}`
        : `REALISTIC EXERCISE REFERENCE PHOTO. Clearly demonstrate only ${input.name}. Movement cues: ${input.instructions.join('; ')}. Safety alignment: ${input.safetyNotes.join('; ')}.`,
      'Exactly one adult athlete shown once, never a split screen or sequence. Full body and all exercise equipment fully visible with generous margins. Premium photorealistic fitness instruction photograph, real human skin and fabric texture, anatomically plausible joints and hands, sharp studio lighting, neutral warm off-white seamless background, camera angle selected to make the technique unmistakable. No illustration, no CGI, no extra people, no ghosted limbs, no overlapping bodies, no impossible anatomy, no labels, no letters, no captions, no arrows, no logo, no watermark, no decorative exercise.',
    ].join(' ');
    const modelInput = config.FAL_IMAGE_MODEL.includes('nano-banana') || config.FAL_IMAGE_MODEL.includes('gemini-3-pro-image')
      ? { prompt, aspect_ratio: '4:3', resolution: '1K', num_images: 1, output_format: 'png', safety_tolerance: '4' }
      : config.FAL_IMAGE_MODEL.includes('kontext')
        ? { prompt, aspect_ratio: '4:3', num_images: 1, output_format: 'png', safety_tolerance: '2' }
        : { prompt, image_size: 'landscape_4_3', num_images: 1, output_format: 'png' };
    const result = await fal.subscribe(config.FAL_IMAGE_MODEL, { input: modelInput });
    const data = result.data as { images?: Array<{ url?: string }> };
    const url = data.images?.[0]?.url;
    if (!url) throw new Error('fal.ai no devolvió una imagen.');
    return { url, prompt, requestId: result.requestId };
  }
}
