-- Exercise catalog used by the gym/home workout variants. Media remains global and reusable:
-- fal.ai assets are generated once and are not visible until human approval.
insert into public.exercises (
  slug, name_es, name_en, instructions_es, instructions_en,
  safety_notes_es, safety_notes_en, movement_type, default_rep_target, default_hold_seconds, active
)
values
('incline-barbell-press', 'Press inclinado con barra', 'Incline barbell press', '["Banco entre 20 y 35 grados", "Escápulas atrás y pies firmes", "Baja hacia la parte alta del pecho", "Empuja con muñecas sobre codos"]', '["Set bench to 20-35 degrees", "Set shoulder blades and feet", "Lower toward upper chest", "Press with wrists over elbows"]', '["No rebotes la barra", "Detente ante dolor de hombro"]', '["Do not bounce the bar", "Stop for shoulder pain"]', 'repetitions', 4, null, true),
('lat-pulldown', 'Jalón al pecho', 'Lat pulldown', '["Fija los muslos", "Inicia bajando los hombros", "Lleva la barra al pecho alto", "Regresa con control"]', '["Secure the thighs", "Start by lowering the shoulders", "Pull toward upper chest", "Return under control"]', '["No lleves la barra detrás de la nuca"]', '["Do not pull behind the neck"]', 'repetitions', 6, null, true),
('leg-press', 'Prensa de pierna', 'Leg press', '["Apoya espalda y pelvis", "Baja con control", "Alinea rodillas y pies", "Empuja sin bloquear bruscamente"]', '["Set back and pelvis", "Lower under control", "Align knees and feet", "Press without forceful lockout"]', '["No permitas que la pelvis se despegue"]', '["Do not let the pelvis lift"]', 'repetitions', 6, null, true),
('lateral-raise', 'Elevación lateral', 'Lateral raise', '["Flexiona ligeramente los brazos", "Eleva en el plano escapular", "Detente a altura del hombro", "Baja lentamente"]', '["Slightly bend the arms", "Raise in the scapular plane", "Stop around shoulder height", "Lower slowly"]', '["Evita balancear el torso"]', '["Avoid swinging the torso"]', 'repetitions', 8, null, true),
('barbell-curl', 'Curl con barra', 'Barbell curl', '["Torso estable", "Codos junto al cuerpo", "Flexiona sin adelantar hombros", "Baja con control"]', '["Keep torso stable", "Keep elbows by the body", "Curl without rolling shoulders", "Lower under control"]', '["Evita usar impulso"]', '["Avoid momentum"]', 'repetitions', 6, null, true),
('triceps-pressdown', 'Extensión de tríceps en polea', 'Triceps pressdown', '["Codos junto al torso", "Extiende hacia abajo", "Pausa al final", "Regresa sin abrir codos"]', '["Keep elbows by torso", "Extend downward", "Pause at the bottom", "Return without flaring elbows"]', '["Mantén las muñecas neutras"]', '["Keep wrists neutral"]', 'repetitions', 8, null, true),
('standing-calf-raise', 'Elevación de pantorrilla de pie', 'Standing calf raise', '["Apoya el antepié", "Desciende en rango cómodo", "Sube sin rebotar", "Pausa y baja lento"]', '["Set the forefoot", "Lower through a comfortable range", "Rise without bouncing", "Pause and lower slowly"]', '["Mantén el tobillo alineado"]', '["Keep the ankle aligned"]', 'repetitions', 8, null, true),
('kneeling-cable-crunch', 'Crunch arrodillado en polea', 'Kneeling cable crunch', '["Arrodíllate estable", "Manos cerca de la cabeza", "Acerca costillas a pelvis", "Regresa con control"]', '["Kneel in a stable position", "Keep hands near the head", "Bring ribs toward pelvis", "Return under control"]', '["No tires solo con los brazos"]', '["Do not pull only with the arms"]', 'repetitions', 8, null, true),
('goblet-squat', 'Sentadilla goblet', 'Goblet squat', '["Carga cerca del pecho", "Pies estables", "Baja entre las piernas", "Sube manteniendo alineación"]', '["Hold load near chest", "Set feet firmly", "Sit down between legs", "Stand while maintaining alignment"]', '["Usa una carga que controles"]', '["Use a controllable load"]', 'repetitions', 6, null, true),
('push-up', 'Flexión de brazos', 'Push-up', '["Manos bajo o algo fuera de hombros", "Cuerpo en bloque", "Baja pecho y cadera juntos", "Empuja el suelo"]', '["Place hands near shoulder width", "Keep body rigid", "Lower chest and hips together", "Push the floor away"]', '["Usa pared o banco si pierdes postura"]', '["Use a wall or bench if form breaks"]', 'repetitions', 6, null, true),
('one-arm-row', 'Remo a una mano', 'One-arm row', '["Apoya la mano libre", "Espalda neutra", "Lleva el codo a la cadera", "Baja sin girar"]', '["Support the free hand", "Keep a neutral spine", "Drive elbow toward hip", "Lower without rotating"]', '["Mantén la cadera quieta"]', '["Keep the hips still"]', 'repetitions', 6, null, true),
('backpack-romanian-deadlift', 'Peso muerto rumano con mochila', 'Backpack Romanian deadlift', '["Carga cerca del cuerpo", "Rodillas suaves", "Cadera atrás", "Extiende la cadera para subir"]', '["Keep load close", "Soften the knees", "Send hips back", "Extend hips to stand"]', '["No redondees la espalda"]', '["Do not round the back"]', 'repetitions', 6, null, true),
('home-reverse-lunge', 'Zancada atrás en casa', 'Home reverse lunge', '["Da un paso atrás", "Desciende ambas rodillas", "Torso estable", "Empuja con la pierna delantera"]', '["Step backward", "Lower both knees", "Keep torso stable", "Push through front leg"]', '["Apóyate si pierdes equilibrio"]', '["Use support if balance is lost"]', 'repetitions', 6, null, true),
('pike-push-up', 'Flexión pica', 'Pike push-up', '["Forma una V invertida", "Manos firmes", "Baja la cabeza entre manos", "Empuja sin colapsar hombros"]', '["Form an inverted V", "Set hands firmly", "Lower head between hands", "Press without collapsing shoulders"]', '["Reduce el rango si no puedes controlarlo"]', '["Reduce range if control is lost"]', 'repetitions', 6, null, true),
('split-squat', 'Sentadilla dividida', 'Split squat', '["Pies en dos rieles", "Talón delantero apoyado", "Rodilla trasera desciende", "Sube con la pierna delantera"]', '["Set feet on two tracks", "Keep front heel planted", "Lower rear knee", "Rise through front leg"]', '["Mantén equilibrio antes de añadir carga"]', '["Establish balance before adding load"]', 'repetitions', 6, null, true),
('glute-bridge', 'Puente de glúteo', 'Glute bridge', '["Pies cerca de la cadera", "Costillas controladas", "Eleva apretando glúteos", "Baja sin arquear"]', '["Set feet near hips", "Keep ribs controlled", "Lift by squeezing glutes", "Lower without arching"]', '["No hiperextiendas la espalda"]', '["Do not hyperextend the back"]', 'repetitions', 8, null, true),
('dead-bug', 'Dead bug', 'Dead bug', '["Cadera y rodillas a 90 grados", "Espalda baja apoyada", "Extiende extremidades contrarias", "Alterna con control"]', '["Set hips and knees at 90 degrees", "Keep low back supported", "Extend opposite limbs", "Alternate under control"]', '["Acorta el recorrido si la espalda se despega"]', '["Shorten the range if the back lifts"]', 'repetitions', 6, null, true),
('backpack-curl', 'Curl con mochila', 'Backpack curl', '["Sujeta la mochila", "Codos junto al cuerpo", "Flexiona sin impulso", "Baja lentamente"]', '["Hold the backpack", "Keep elbows by body", "Curl without momentum", "Lower slowly"]', '["Revisa que cierres y asas estén firmes"]', '["Check that zippers and handles are secure"]', 'repetitions', 8, null, true),
('chair-triceps-dip', 'Fondo de tríceps en silla', 'Chair triceps dip', '["Asegura la silla", "Manos cerca de cadera", "Flexiona codos atrás", "Empuja para volver"]', '["Secure the chair", "Set hands near hips", "Bend elbows backward", "Press to return"]', '["Silla contra una pared; limita rango ante molestia"]', '["Brace chair against wall; limit range if uncomfortable"]', 'repetitions', 6, null, true),
('single-leg-calf-raise', 'Pantorrilla a una pierna', 'Single-leg calf raise', '["Apóyate ligeramente", "Eleva un pie", "Sube el talón", "Pausa y baja lento"]', '["Use light support", "Lift one foot", "Raise the heel", "Pause and lower slowly"]', '["Mantén el tobillo alineado"]', '["Keep the ankle aligned"]', 'repetitions', 8, null, true)
on conflict (slug) do update set
  name_es = excluded.name_es,
  name_en = excluded.name_en,
  instructions_es = excluded.instructions_es,
  instructions_en = excluded.instructions_en,
  safety_notes_es = excluded.safety_notes_es,
  safety_notes_en = excluded.safety_notes_en,
  movement_type = excluded.movement_type,
  default_rep_target = excluded.default_rep_target,
  default_hold_seconds = excluded.default_hold_seconds,
  active = excluded.active,
  updated_at = now();
