import type { Metadata } from "next";
import { LegalPage } from "@/components/LegalPage";

export const metadata: Metadata = { title: "Términos y condiciones", description: "Términos de uso de VITAMATE." };

export default function TermsPage() {
  return <LegalPage eyebrow="Condiciones de uso" title="Términos y condiciones" updated="Última actualización: 14 de julio de 2026" sections={[
    ["1. Aceptación", <p key="acceptance">Al crear una cuenta o utilizar VITAMATE aceptas estos términos y el aviso de privacidad. Si no estás de acuerdo, no utilices el servicio. Debes contar con capacidad legal suficiente; la versión inicial está dirigida a personas adultas.</p>],
    ["2. Naturaleza del servicio", <div key="nature"><p>VITAMATE ofrece herramientas de organización, estimación y orientación de bienestar: planes de entrenamiento y alimentación, seguimiento, conversación asistida por IA y consulta de fuentes de terceros.</p><p>No es un servicio médico, psicológico ni de nutrición clínica; no diagnostica, prescribe medicamentos ni atiende emergencias. Ante síntomas, lesiones, trastornos de conducta alimentaria o condiciones médicas, consulta a un profesional.</p></div>],
    ["3. Cuenta y uso responsable", <p key="account">Debes proporcionar información razonablemente correcta, proteger el acceso a tu cuenta y revisar las recomendaciones antes de actuar. No puedes vulnerar el servicio, automatizar abuso, extraer bases de datos, cargar contenido ilícito ni usar VITAMATE para dañar a otra persona.</p>],
    ["4. Entrenamiento y seguridad", <p key="training">Ajusta el ejercicio a tu capacidad, técnica, equipo y entorno. Detén la actividad ante dolor agudo, mareo, dificultad respiratoria inusual u otra señal de alarma. Las imágenes de técnica sólo se publican tras revisión interna, pero no sustituyen supervisión presencial.</p>],
    ["5. Nutrición, precios y fuentes", <div key="nutrition"><p>Calorías, macronutrientes, porciones, reconocimiento fotográfico y costos son estimaciones. Verifica etiquetas, ingredientes, alergias y cantidades. Los precios pueden variar por tienda, marca, presentación, disponibilidad, ciudad y fecha.</p><p>VITAMATE usa, entre otras fuentes, USDA FoodData Central, Open Food Facts, PROFECO e INEGI. Su uso no implica patrocinio o aval de esas instituciones. Consulta la <a href="/fuentes">metodología y fuentes</a>.</p></div>],
    ["6. Suscripción y pagos", <div key="billing"><p>Los precios, periodicidad e impuestos aplicables se mostrarán antes del pago. Los cobros web son procesados por Stripe. La renovación es automática hasta que se cancele; la cancelación impide renovaciones futuras y el acceso continúa hasta concluir el periodo pagado, salvo disposición legal distinta.</p><p>Reembolsos, promociones y pruebas se regirán por las condiciones mostradas al contratar y la normativa de protección al consumidor aplicable.</p></div>],
    ["7. Contenido e inteligencia artificial", <p key="content">Conservas los derechos que tengas sobre el contenido que aportas y nos autorizas a procesarlo sólo para operar, proteger y mejorar el servicio conforme al aviso de privacidad. Las respuestas de IA pueden ser incompletas o equivocadas; tú debes verificarlas antes de tomar decisiones relevantes.</p>],
    ["8. Disponibilidad y cambios", <p key="availability">Podemos actualizar funciones, suspender mantenimiento o limitar accesos por seguridad. Procuraremos comunicar cambios materiales. No garantizamos funcionamiento ininterrumpido ni compatibilidad permanente con dispositivos o servicios de terceros.</p>],
    ["9. Responsabilidad", <p key="liability">En la medida permitida por la ley, VITAMATE no responde por decisiones tomadas ignorando advertencias, información incorrecta del usuario, fallas de terceros o uso fuera del propósito del servicio. Nada en estos términos limita derechos irrenunciables del consumidor.</p>],
    ["10. Contacto y ley aplicable", <p key="contact">Para soporte escribe a contacto@vitamate.mx. Estos términos se interpretarán conforme a las leyes mexicanas y sin perjuicio de la competencia de PROFECO y demás autoridades aplicables. Antes del lanzamiento se incorporará el domicilio y jurisdicción contractual definitiva.</p>],
  ]} />;
}
